### ISSUE TITLE
Error: java.lang.IllegalArgumentException: interface x.xx.xxx is not visible from class loader

### ISSUE THREAD

**Issue by ufologist** [MarkusJx/node-java-bridge#22]
node: v14.19.0
java-bridge: 2.1.1

In jar use `java.lang.reflect.Proxy`'s `Proxy.newProxyInstance` via ClassLoader and `importClassAsync` maybe existence conflict.

full error message is here
```
(node:19648) UnhandledPromiseRejectionWarning: Error: java.lang.IllegalArgumentException: interface x.xx.xxx is not visible from class loader
    at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
    at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
    at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
    at java.lang.reflect.WeakCache.get(WeakCache.java:127)
    at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
    at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
    at src\jni\java_env_wrapper.rs:636
    at src\jni\java_env_wrapper.rs:303
```

**Comment by MarkusJx** [comment]
Could you please provide a minimal reproducible example?

**Comment by ufologist** [comment]
Java code

```java
// com/test/App.java
package com.test;
 
import java.lang.reflect.Proxy;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
 
public class App {
    public static void main(String[] args) {
        IVehical car = new Car();
 
        IVehical vehical = (IVehical)Proxy.newProxyInstance(
            // use this ClassLoader will cause Error
            Thread.currentThread().getContextClassLoader(),
            // change to this will fix the Error
            // car.getClass().getClassLoader(),

            Car.class.getInterfaces(),
            new VehicalInvacationHandler(car));

        vehical.run();

        System.out.println(vehical.getClass());
    }
}

interface IVehical {
    void run();
}

class Car implements IVehical {
    public void run() {
        System.out.println("Car");
    }
}

class VehicalInvacationHandler implements InvocationHandler {
    private final IVehical vehical;

    public VehicalInvacationHandler(IVehical vehical){
        this.vehical = vehical;
    }
 
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        System.out.println("---------before-------");
        Object invoke = method.invoke(vehical, args);
        System.out.println("---------after-------");
 
        return invoke;
    }
}
```

JS code
```javascript
// node-java.js
const {
    importClassAsync,
    classpath,
} = require('java-bridge');

classpath.append('./test.jar');

(async function() {
    const App = await importClassAsync('com.test.App');
    await App.main([]);
})();
```

```
> node node-java.js

(node:14060) UnhandledPromiseRejectionWarning: Error: java.lang.IllegalArgumentException: interface com.test.IVehical is not visible from class loader
    at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
    at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
    at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
    at java.lang.reflect.WeakCache.get(WeakCache.java:127)
    at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
    at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
    at com.test.App.main(App.java:11)
    at src\jni\java_env_wrapper.rs:726
    at src\jni\java_env_wrapper.rs:303
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MarkusJx** [comment]
This issue should be fixed in the latest release: https://github.com/MarkusJx/node-java-bridge/releases/tag/v2.1.4

Feel free to re-open this issue if you still experience this error or create a new issue if you encounter another error

**Comment by ufologist** [comment]
`java-bridge@2.1.4` fix this issue, thanks!
