### ISSUE TITLE
javax SAX problem

### ISSUE THREAD

**Issue by skvlakov** [MarkusJx/node-java-bridge#5]
Hello,

Problem below:

node version: v16.15.1
Example:
```javascript
const java = require('@markusjx/java');
//----------------
(async function() {
  const libPath = await java.findJVM();
  console.log("Java JVM path: ", libPath);
  java.ensureJVM(null, java.java_version.VER_1_8);
  var SAXException = java.importClass('org.xml.sax.SAXException');
  var SAXParserFactory = java.importClass('javax.xml.parsers.SAXParserFactory');
})()
```
```
> set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131\jre

> node scripts\test1-markusjx-java.js
Java JVM path: C:\Program Files\Java\jdk1.8.0_131\jre\bin\server\jvm.dll
```
```diff
- ...\node_modules\@markusjx\java\index.js:79
-       return native.java.getClass(classname).getClassConstructor();
                                               ^
-    Error: Invalid argument
-       at Object.importClass (...\node_modules\@markusjx\java\index.js:79:48)
-       at ...\scripts\test1-markusjx-java.js:8:31
```
Maybe problem is with "protected constructor" ? [SAXParserFactory](https://docs.oracle.com/en/java/javase/12/docs/api/java.xml/javax/xml/parsers/SAXParserFactory.html#%3Cinit%3E())()

**Comment by MarkusJx** [comment]
Hi,
I'll look into this and let you know, once I've got some results :)

**Comment by MarkusJx** [comment]
Your problem should be fixed with the latest patch, you can try it out by installing the package using
```sh
npm i MarkusJx/node-java-bridge#fix/protectedConstructors
```

Let me know if that worked, so I can close this issue, if resolved

**Comment by skvlakov** [comment]
Thank you, it works - you were quick.
